/*
 * NewJFrame.java
 *
 * Created on February 24, 2011, 9:44 AM
 */
package programlatih160java;

import java.sql.*;
import javax.swing.JTable;

/**
 *
 * @author  sammylie
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        tampilTabel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
     private Object[] []getData(){
        String user="root";
        String pwd ="admin";
        String host="localhost";
        String db="dbpenggajian";
        String url="";

        Object[][] data1= null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+
               db +"?user=" + user +
               "&password="+ pwd;

            Connection conn=
                    DriverManager.getConnection(url);

            Statement stmt = conn.createStatement();
            ResultSet rslt = stmt.executeQuery("Select * from absen");

            rslt.last();
            int rowCount= rslt.getRow();
            rslt.beforeFirst();

            data1= new Object[rowCount][3];
            int no=-1;
            while (rslt.next()) {
                no=no+1;
                data1[no][0]=rslt.getString("Nokartu");
                data1[no][1]=rslt.getString("Nip");
                data1[no][2]=rslt.getString("Warna");
          }

          stmt.close();
          conn.close();

       }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

       }

        return data1;
    }

     private void tampilTabel() {

         String[] columnNames = 
           {"Nokartu", "Nip","Warna"};

        JTable table = new JTable(getData(), columnNames);

        jScrollPane1.setViewportView(table);       
    }
}

  
