/*
 * FormUser.java
 *
 * Created on February 24, 2011, 5:58 PM
 */

package formuser;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.JOptionPane;


/**
 *
 * @author  sammy
 */
public class FormUser extends javax.swing.JFrame {
private String user = "root";
private String password = "admin";
private String host = "localhost";
private String db = "latihan";
private String urlvalue = "";
private Connection conn = null;
    /** Creates new form FormUser */

    public FormUser() {
        initComponents();
        showTable();
}
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 private Object[][] getData()
        {
        Object[][] data1 = null;

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            urlvalue = "jdbc:mysql://" + host + "/" + db + "?user=" + user + "&password=" + password;
             conn = DriverManager.getConnection(urlvalue);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from user");

            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();

            data1 = new Object[rowCount][3];

            int no=-1;
               while (rs.next())
{
                no=no+1;
                data1[no][0]=rs.getString("user_id");
                data1[no][1]=rs.getString("password");
                data1[no][2]=rs.getString("jabatan");
               }
               st.close();
               conn.close();
        }

        catch (ClassNotFoundException e)
        {
JOptionPane.showMessageDialog(this, "kelas Tidak ditemukan", "Driver gagal", JOptionPane.ERROR_MESSAGE);
        }

        catch (SQLException e)
        {
JOptionPane.showMessageDialog(this, "Pengambilan Data Gagal", "Informasi", JOptionPane.ERROR_MESSAGE);
        }
        return data1;
        }

private void showTable ()
    {
        String[] columnNames = {"User ID","Password","Jabatan"};

        JTable table = new JTable (getData(),columnNames);
        jScrollPane1.setViewportView(table);
    }
}
